### PR TITLE
Add 'WinFuture.de' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22winfuture%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22WinFuture.de%22%2C%22address%22%3A%22Sebastian%20Kuhbach%5CnDudenstr.%2010%5Cn10965%20Berlin%5Cn%22%2C%22phone%22%3A%22%2B49%2030%2027908360%22%2C%22email%22%3A%22sk%40winfuture.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.winfuture.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.winfuture.de%2Fimpressum%22%2C%22https%3A%2F%2Fwww.winfuture.de%2Fimpressum%23datenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1265%22%5D%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Review by baltpeter — APPROVED** [review]
Thank you!

**Comment by WebworkrNet** [comment]
1. Why was this entry assigned to the category "Advertising"? Shouldn't only the primary business purpose be stated?
2. Why was the name "Sebastian Kuhbach" removed from the record? According to my assessment, he is the website operator according to the imprint. Another stomach ache regarding the personal data?

**Comment by baltpeter** [comment]
>     1. Why was this entry assigned to the category "Advertising"? Shouldn't only the primary business purpose be stated?

See the description in the schema:

https://github.com/datenanfragen/data/blob/eed67a7999cd0cf3b09be2d26cf0d98b5742b667/schema.json#L27

We often don't have a category that perfectly fits a record, so we tend to interpret the existing ones pretty widely. But I don't know this website well, if you think "ads" isn't fitting, we can remove it.

>     2. Why was the name "Sebastian Kuhbach" removed from the record? According to my assessment, he is the website operator according to the imprint. Another stomach ache regarding the personal data?

Yeah, we try to only process personal data in our company database where absolutely necessary (see #1287). In this case, I am confident enough that correspondence will also arrive just fine without the operator's personal name.

**Pull request merged**
