### PR TITLE
Add 'Lidl (Filialgeschäft)' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_lidl_1696852076229%2Fcompanies%2Flidl.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
Related to #2395, #2396, #2397.

**Comment by baltpeter** [comment]
This one is unfortunately really not easy. There's two problems:

* According to https://www.lidl.de/c/datenschutz/s10007528 (as you mentioned in the comment), there is no single controller that is responsible for all stores. There are literally hundreds of "Lidl Vertriebs-GmbH & Co. KG"s all over Germany (cf. https://www.northdata.de/Lidl+Vertriebs-GmbH+%26+Co%20+KG). And as far as I can tell, those are not different establishments of the same company, but actual separate legal entities. So, we cannot just lump them all into the same record. Unless we can find a single parent company (I couldn't), we would need a record for each one.
* As per our policy (currently unfortunately unwritten, but I am planning to work on that, cf. #2336), every piece of information in the record needs to have a publicly available (online) source. This is to ensure that a) anyone can actually verify the information and b) we want to implement automatic change detection in the future. As such, a piece of paper in a store somewhere (or a photo of that) won't do.

  However, that's not too much of a problem in this case. The privacy policy on the website in combination with the relevant Handelsregistereintrag should be fine.

**Review by fm — COMMENTED** [review]
Apologies, clicked the wrong button.

**Pull request closed without merging**
