### PR TITLE
Add 'VNR Verlag für die Deutsche Wirtschaft AG' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22simplify%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22school%22%2Cnull%5D%2C%22name%22%3A%22VNR%20Verlag%20f%C3%BCr%20die%20Deutsche%20Wirtschaft%20AG%22%2C%22address%22%3A%22Theodor-Heuss-Str.%202-4%5Cn53177%20Bonn%22%2C%22phone%22%3A%22%2B49%20228%20955066004%22%2C%22email%22%3A%22datenschutzbeauftragter%40vnr.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.simplify.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.simplify.de%2Fservice-rechtliches%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1251%22%5D%2C%22comments%22%3A%5B%22Verlag%20betreibt%20vernutlich%20noch%20weitere%20Angebote%20neben%20Sympily.%22%5D%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
After contacting VNR Verlag, I would like to propose the following changes:

### Also operates: 
**https://www.simplify.de**

### Website 
~~http://www.simplify.de~~
**https://www.vnrag.de**

### Source
~~https://www.simplify.de/service-rechtliches/datenschutz~~

**https://www.vnrag.de/datenschutz
https://www.simplify.de/service-rechtliches/datenschutz**

**Comment by baltpeter** [comment]
Thanks! As they all share the same contact details, I have also added the remaining brands from: https://www.vnrag.de/fachverlage/

> After contacting VNR Verlag

Have you sent them a request? And if so, which identification details (name, email, …) have you provided? If we know those, we can promote the record from a quality of 'verified' to 'tested', so it gets a green checkmark in the search.

**Comment by WebworkrNet** [comment]
> Have you sent them a request? And if so, which identification details (name, email, …) have you provided?

That is correct.

I have provided the first name, surname and email address concerned.

It is required that the request for information is made from the email address that was given for identification. The provider wants to check whether the requester is also the owner of this mailbox. 

Example:
Sender foo@example.org wants information about bar@example.org.
NOT OK

Sender foo@example.org would like information about foo@example.org.
OK

Alternatively, a received email can be forwarded. This is a simple alternative if foo@example.org is an email forwarding without a mailbox.

**Comment by WebworkrNet** [comment]
_Addition:_

### Also operates:
https://www.sekada.de
https://www.sekretaerinnen.de

### Source:
https://www.sekada.de/footernavi/service-rechtliches/datenschutz/

**Comment by WebworkrNet** [comment]
**Also operates:**
https://verlag.orgenda.de

**Source:**
https://verlag.orgenda.de/datenschutz/

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
