### PR TITLE
Add 'emil energie GmbH' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_emil-energie_1700897803788%2Fcompanies%2Femil-energie.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
### This dataset can be marked as "`tested`".

**Personal data provided at data request:**

- [ ] Email address
- [x] Name
- [x] Address
- [ ] Birth date
- [ ] Other

**Evidence requested to confirm identity:**
 
- [x] No provision of evidence
- [ ] Requests by email must be made from the same email address that is the subject of the request. This should be noted if the submitted address is an email forwarding address.
- [ ] Birth date
- [ ] Copy of ID

**Comment by mal-tee** [comment]
> You can contact me if you have any questions.

You've used the regular address instead of the contact address for the DSB. Was there any specific reason for that decision?

**Comment by WebworkrNet** [comment]
I probably wanted to accommodate both the address of the person responsible and those of the data protection officer.

In the afterno (after the data record was created), it turned out that when I contacted (`datenschutz@`), the Emil customer service always replied (`service@`).

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
