### PR TITLE
Add 'Andreas Kollmer' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22eclipse-software%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22Andreas%20Kollmer%22%2C%22runs%22%3A%5B%22https%3A%2F%2Fwww.neuverlieben.com%22%5D%2C%22address%22%3A%22Azuero%20Business%20Center%5CnSuite%20456%5CnAvenida%20Perez%20Chitre%5Cn0601-00395%20Panama%22%2C%22email%22%3A%22mail%40neuverlieben.com%22%2C%22web%22%3A%22http%3A%2F%2Fwww.eclipse-software.net%22%2C%22sources%22%3A%5B%22http%3A%2F%2Fwww.eclipse-software.net%22%2C%22https%3A%2F%2Fwww.neuverlieben.com%2Fimpressum.php%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1289%22%5D%2C%22comments%22%3A%5B%22Weitere%20Webseiten%20im%20Angebot%2C%20siehe%20http%3A%2F%2Fwww.eclipse-software.net%22%5D%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Review by mal-tee — APPROVED** [review]
Thank you!

**Comment by WebworkrNet** [comment]
@mal-tee I had taken the e-mail address `mail@neuverlieben.com` from the privacy policy https://www.neuverlieben.com/impressum.php.
And that is why I had given her preference over `delphi@neuverlieben.com`.

**Comment by WebworkrNet** [comment]
@mal-tee I had taken the name `Andreas Kollmer` from the copyright. If it is a sole trader or freelancer, as it looks to me, then the name should be added to the company name. I assume that we are using German standards as a basis.

**Comment by mal-tee** [comment]
> I had taken the e-mail address mail@neuverlieben.com from the privacy policy neuverlieben.com/impressum.php.
And that is why I had given her preference over delphi@neuverlieben.com.

The PP states it's just a regular support email address, as is `delphi@`. According to https://www.eclipse-software.net/ `delphi@` also covers the other webpages, and therefore allows use to include another webpage in the same entry.

**Comment by mal-tee** [comment]
I see no reason to add a full name if we don't have to. The existing data is sufficient.

**Pull request merged**
