### PR TITLE
Update 'Reddit, Inc.' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22reddit%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22Reddit%2C%20Inc.%22%2C%22address%22%3A%22520%203rd%20Street%5CnSan%20Francisco%5CnCA%2094107%5CnUnited%20States%20of%20America%22%2C%22email%22%3A%22eurepresentative%40reddit.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.reddit.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.redditinc.com%2Fpolicies%2Fprivacy-policy%22%2C%22https%3A%2F%2Fwww.bloomberg.com%2Fprofiles%2Fcompanies%2F0893288D%3AUS-reddit-inc%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F669%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F893%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22Username%22%2C%22type%22%3A%22input%22%7D%5D%2C%22request-language%22%3A%22en%22%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by bcye** [comment]
changed the email, it's mentioned in the contact us section of the PP

**Comment by baltpeter** [comment]
Thanks, @bcye. The privacy policy still also says:

> All other data subject and consumer requests under data protection laws should be sent via email to redditdatarequests@reddit.com from the email address that you have verified with your Reddit account.

Thus, I am honestly not quite sure which one is better. Have you tried using eurepresentative@reddit.com to send a request to Reddit. If you can confirm that the new one works better, we can definitely switch to that.

**Comment by bcye** [comment]
I've sent mine to the representative address and it's forwarded to their support legal team, which basically just tell you to go into your settings and click delete account.

**Comment by mal-tee** [comment]
Interesting :D

Seems like both addresses "do the same thing". Imo "redditdatarequests@reddit.com" sounds more privacy-related imo. So we should keep that email and maybe add the other as a "comment" in the entry's `comments`?

**Comment by bcye** [comment]
Might be worth mentioning, if you want your posts deleted they require you to go through them one by one yourself, as they don't count them as personal data.

**Comment by mal-tee** [comment]
Oh thats interesting! Thank you. I agree, that is worth mentioning in the record :D

**Review by baltpeter — APPROVED** [review]

**Comment by baltpeter** [comment]
> Might be worth mentioning, if you want your posts deleted they require you to go through them one by one yourself, as they don't count them as personal data.

It would great if you could post that as a comment on the [company page](https://www.datarequests.org/company/reddit). Those are meant for sharing your experiences with the data protection practices of the respective company.

**Comment by bcye** [comment]
@baltpeter sure

**Pull request merged**
