### PR TITLE
Update 'ERGO Direkt Versicherungen' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22ergo-direkt%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22ERGO%20Direkt%20Versicherungen%22%2C%22runs%22%3A%5B%22ERGO%20Direkt%20Lebensversicherung%20AG%22%2C%22ERGO%20Direkt%20Versicherung%20AG%22%2C%22ERGO%20Direkt%20Krankenversicherung%20AG%22%2C%22ERGO%20Vorsorge%20Lebensversicherung%20AG%22%2C%22ERGO%20Krankenversicherung%20AG%22%2C%22ERGO%20Versicherung%20AG%22%2C%22Victoria%20Lebensversicherung%20AG%22%2C%22DKV%20Deutsche%20Krankenversicherung%20AG%22%2C%22ERGO%20Reiseversicherung%20AG%22%2C%22ERGO%20Lebensversicherung%20AG%22%2C%22ERGO%20Direkt%20AG%22%5D%2C%22address%22%3A%22Karl-Martell-Stra%C3%9Fe%2060%5Cn90344%20N%C3%BCrnberg%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20800%204441000%22%2C%22email%22%3A%22datenschutz%40ergo.de%22%2C%22web%22%3A%22https%3A%2F%2Fergodirekt.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fergodirekt.de%2Fde%2Fdatenschutzunddatensicherheit.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F42%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1396%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by fm** [comment]
@WebworkrNet Great! What information did they request so I can add it to `required-elements`?

**Comment by WebworkrNet** [comment]
@fm The request is still ongoing. To date, no evidence has been requested to confirm my identity.

**Comment by baltpeter** [comment]
I have merged the changes to `runs` in eea6b34.

@WebworkrNet I'll close this for now but as @fm if you can tell use the necessary identification details (either here or through a new suggestion), we can promote ERGO to `tested`. Thanks!

**Comment by WebworkrNet** [comment]
@baltpeter OK

**Pull request closed without merging**
