### PR TITLE
Add 'Lindner IT UG (haftungsbeschränkt)' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_lindnerit_1691759134237%2Fcompanies%2Flindnerit.json )**

### CODE REVIEW

**Comment by deeprobin** [comment]
I have taken the liberty of registering my company with you in order to provide even more transparency in the direction of data storage.

If that's okay with you, feel free to merge.

**Review by mal-tee — CHANGES_REQUESTED** [review]
Thank you!

Your privacy policy contains a different phone no.:
> Telefon: +49 162 3199554

Usually we prefer the phone no. intended for privacy-related inquires. 

Please also add a source, e.g. link to the privacy policy or imprint, for every data point in the record.

**Comment by deeprobin** [comment]
@mal-tee The privacy policy was out of date. 
I just changed it to the main phone number to address legal but also privacy issues (`+49 7931 5636150`).

**Comment by deeprobin** [comment]
I'm not able to commit to this Branch, because it was created by the bot.

Sources are: https://lindnerit.io/de/privacy-policy & https://lindnerit.io/de/legal-details

**Review by mal-tee — APPROVED** [review]

**Comment by mal-tee** [comment]
Thank you!

**Pull request merged**
