### PR TITLE
New company suggestion: 'Barmenia Versicherungen a. G.'

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22barmeniade%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22Barmenia%20Versicherungen%20a.%20G.%22%2C%22runs%22%3A%5B%22Barmenia%20Allgemeine%20Versicherungs-AG%22%2C%22Barmenia%20Krankenversicherung%20AG%22%2C%22Barmenia%20Lebensversicherung%20a.%20G.%22%5D%2C%22address%22%3A%22Barmenia-Allee%201%5Cn42119%20Wuppertal%5CnDeutschland%22%2C%22phone%22%3A%220202%20438-00%22%2C%22email%22%3A%22datenschutz%40barmenia.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.barmenia.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.barmenia.de%2Fdeu%2Fbde_privat%2Fdatenschutz.xhtml%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F691%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22%2C%22optional%22%3Afalse%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**

### CODE REVIEW

**Comment by m-rey** [comment]
That was fast!
Now that the community edits create a PR instead of an issue, to fix suggestions, I need to make the changes in the corresponding branch of `datenanfragen-community-edits/data`, right?

In that case, could I also get commit rights to `datenanfragen-community-edits/data`?

On another note, if each suggestion creates a PR, does this trigger the CI every time? If so, I remember that this was a problem before. Has this improved?

**Comment by baltpeter** [comment]
> That was fast!

Yep, thanks to the great changes by @mal-tee and @zner0L, reviewing suggestions is a lot easier now!

> Now that the community edits create a PR instead of an issue, to fix suggestions, I need to make the changes in the corresponding branch of datenanfragen-community-edits/data, right?

Exactly, as you are a maintainer in this repo, you should have the rights to write directly to the branch (the PRs automatically tick the 'Allow edits by maintainers' checkbox). You should be able to just use the 'Edit file' button in the 'Files changed' tab. Alternatively, you should also be able to directly push to the respective branch from the desktop.

Let me know if this doesn't work.

> On another note, if each suggestion creates a PR, does this trigger the CI every time? If so, I remember that this was a problem before. Has this improved?

Yes, each suggestion triggers the CI checks. That should not be an issue though, as they are very lightweight and complete in a matter of seconds. This also has the benefit of directly highlighting any potential problems directly under the suggestion.

**Comment by m-rey** [comment]
> Let me know if this doesn't work.

Maybe I did it wrong, but when navigating to the corresponding branch of a PR and trying to upload an updated file to it via the web interface, the following error message appears:
```
Uploads are disabled.
File uploads require push access to this repository.
```

I also don't see a 'Edit file' button in the 'Files changed' tab of the PR.

**Comment by zner0L** [comment]
> I also don't see a 'Edit file' button in the 'Files changed' tab of the PR.

There should be a "Edit File" Link in the three dot menu in the "Files Changed" tab on the top right of each file. Do you see that? Otherwise, I would suspect your role does not have the right permissions (even though the checkbox explicitly says "Maintainers"). 

Let me now!

**Comment by m-rey** [comment]
Okay, my bad. Thanks for the help! 

I was looking at an already merged PR. I guess that's why I couldn't edit the file.

**Pull request merged**
