### PR TITLE
Add 'nepatec GmbH' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_nepatec_1668533230011%2Fcompanies%2Fnepatec.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
### This dataset can be marked as "`tested`".

**Personal data provided at data request:**

- [x] Email address
- [x] Name
- [ ] Address
- [ ] Birth date
- [ ] Other

**Evidence requested to confirm identity:**
 
- [ ] No provision of evidence
- [ ] Requests by email must be made from the same email address that is the subject of the request. This should be noted if the submitted address is an email forwarding address.
- [ ] Birth date
- [X] Copy of ID

**Comment by WebworkrNet** [comment]
`"[...] in order to comply with your request, we need proof of identity. Please send us a copy of your identification. For data protection reasons, please use a secure means of communication such as fax. [...]"`

Personally, I do not consider a fax to be a secure channel because it also lacks encryption.

**Comment by WebworkrNet** [comment]
Also operates:
- edocbox.de
- edocbox.nepatec.de
- nepatec.de/showOfficialIps.php

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
