### PR TITLE
Add 'dtv Verlagsgesellschaft mbH & Co. KG' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22dtv%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22dtv%20Verlagsgesellschaft%20mbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22Tumblingerstra%C3%9Fe%2021%5Cn80337%20M%C3%BCnchen%22%2C%22email%22%3A%22datenschutz%40dtv.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.dtv.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.dtv.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1274%22%5D%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
Email to datenschutz@dtv.de cannot be delivered.

```
Fehler bei der Nachrichtenzustellung an folgende Empfänger oder Gruppen:

datenschutzdtv@activemind.de
Die eingegebene E-Mail-Adresse konnte nicht gefunden werden. Überprüfen Sie die E-Mail-Adresse des Empfängers, und versuchen Sie, die Nachricht erneut zu senden. Wenden Sie sich an den Helpdesk, falls das Problem weiterhin besteht.
```


I propose to defer the pull request until the matter is resolved.

**Comment by WebworkrNet** [comment]
The self-disclosure requested via verlag@dtv.de was answered in less than half a working day by kundenservice@dtv.de.

**Comment by WebworkrNet** [comment]
On the other hand, I have not yet received a reply to the note that emails to datenschutz@dtv.de cannot be delivered.

**Comment by WebworkrNet** [comment]
@baltpeter thank you for your question, I would follow your suggestion and update the changes later.

**Comment by baltpeter** [comment]
@WebworkrNet If you want to use kundenservice@dtv.de, I think it's easier if I just make the changes here in the PR.

**Comment by WebworkrNet** [comment]
@baltpeter, what do you think of a public notice that the emails to the address "datenschutz@dtv.de" are currently not being delivered?

**Comment by WebworkrNet** [comment]
> @WebworkrNet If you want to use kundenservice@dtv.de, I think it's easier if I just make the changes here in the PR.

Yes, of course, go ahead. I had already understood your suggestion that way.

**Comment by baltpeter** [comment]
> Yes, of course, go ahead. I had already understood your suggestion that way.

Ah okay, I misunderstood you. Will do.

> what do you think of a public notice that the emails to the address "datenschutz@dtv.de" are currently not being delivered?

I would prefer not to have that in the record. The notes there are displayed pretty prominently and should contain things that are important to the user (like the information that the phone number is not free, for example). I'd think that users of our site rely on the information in our company database anyway and don't check the privacy policy themselves, so they probably wouldn't know of datenschutz@dtv.de anyway.

But if you want to add that as a comment on the company page once that's live (including the info that you've contacted them about that), I think that would be valuable. That's also the place we've intended for such discussions.

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
