### PR TITLE
Add 'RescueTime' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22rescuetime%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22RescueTime%22%2C%22phone%22%3A%22888-215-8635%22%2C%22email%22%3A%22dpo%40rescuetime.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.rescuetime.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fblog.rescuetime.com%2Fpersonal-data-gdpr%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1259%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Review by fm — COMMENTED** [review]
@baltpeter I found the address in the WA Secretary of State, but their search system doesn't have permalinks, so I didn't add it. Should I still add it as a source?

URL: https://ccfs.sos.wa.gov/#/BusinessSearch

**Comment by baltpeter** [comment]
Thanks, @fm. We do really need to have a permalink to a source containing the address to allow for automatic verification. In these cases, I usually use [OpenCorporates](https://opencorporates.com/). They crawl most of the publicly available company registers and _do_ offer permalinks to the records, including [this one](https://opencorporates.com/companies/us_wa/602852484).

Of course, where available official sources are preferred. And in fact, from the sources on the OC page, I just learned, that there are actually permalinks on the WA SoS website (if you know how they work): https://www.sos.wa.gov/corps/business.aspx?ubi=602852484 :D

**Comment by baltpeter** [comment]
Oh nvm, the "official permalink" doesn't include the address. :/ So, we do have to use the OC one after all…

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
