### PR TITLE
Add 'Nokia Corporation' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22nokia%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Nokia%20Corporation%22%2C%22address%22%3A%22Karakaari%207%5CnP.O.%20Box%20226%5CnFI-00045%20Nokia%20Group%5CnFinland%22%2C%22web%22%3A%22https%3A%2F%2Fwww.nokia.com%2Fde_int%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.nokia.com%2Fde_int%2Fprivacy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1258%22%5D%2C%22comments%22%3A%5B%22Es%20ist%20keine%20Emailadresse%20angegeben.%20Das%20Kontaktformular%20ist%20auf%201000%20Zeichen%20begrenzt.%20Der%20Mustertext%20mus%20drastisch%20gek%C3%BCrzt%20werden.%20Die%20Webseite%20ist%20nicht%20komplett%20in%20deutscher%20Sprache%20verf%C3%BCgbar.%20Trotz%20gew%C3%A4hlter%20deutscher%20Spracche%20muss%20die%20Sprache%20des%20Formulars%20noch%20einmal%20auf%20deutsch%20umgestellt%20werden.%22%5D%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
The contact details are valid for other countries. Exactly which ones these are would still have to be researched.

**Comment by WebworkrNet** [comment]
The contact request must be made from the email address that is the subject of the request. It must therefore be entered as the sender in the contact form.

**Comment by WebworkrNet** [comment]
Contacting via form opens a Zendesk ticket. The complete enquiry can then be sent again in full, as a self-sent email is not subject to a character limit.

It is unclear whether direct contact via online.global@nokia.com would also be possible. Some ticket systems return an error message if the initial contact is not made via the form.

**Comment by WebworkrNet** [comment]
The email server rejects emails with the error message "550 5.4.1 Recipient address rejected: Access denied." if a suitable SMTP server is NOT set up for this address. This excludes pure email forwarding. Email aliases, even from the same domain of the forwarding address, are not possible.

**Review by fm — APPROVED** [review]
@baltpeter I think this would be good enough, the text makes it sound like all other countries should also report to Finland for DPO. 

Should the comments be put in English instead given it would apply to all EU countries?
https://www.nokia.com/notices/privacy/

**Comment by baltpeter** [comment]
> @baltpeter I think this would be good enough, the text makes it sound like all other countries should also report to Finland for DPO.

I agree.

> Should the comments be put in English instead given it would apply to all EU countries?
> [nokia.com/notices/privacy](https://www.nokia.com/notices/privacy/)

Yep. And we should also link the contact form (that currently only works through a comment, but a separate field for that is planned, see datenanfragen/website#401).

**Review by baltpeter — APPROVED** [review]
Thank you!

**Comment by WebworkrNet** [comment]
>Yep. And we should also link the contact form (that currently only works through a comment, but a separate field for that is planned, see datenanfragen/website#401).

Good idea

**Pull request merged**
