### PR TITLE
Update 'STAGE ENTERTAINMENT Marketing & Sales GmbH' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_stage-entertainment-de_1689778533058%2Fcompanies%2Fstage-entertainment-de.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
Related to #959.

**Comment by WebworkrNet** [comment]
### This dataset can be marked as "`tested`".

**Personal data provided at data request:**

- [x] Email address
- [x] Name
- [x] Address
- [ ] Birth date
- [ ] Other

**Evidence requested to confirm identity:**
 
- [X] No provision of evidence
- [ ] Requests by email must be made from the same email address that is the subject of the request. This should be noted if the submitted address is an email forwarding address.
- [ ] Birth date
- [ ] Copy of ID

**Comment by WebworkrNet** [comment]
It was mentioned in #959 that no proof of identity is required. However, I may not have worded this clearly enough or the reference may have been inadvertently overlooked. Therefore I have opened this new pull request.

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
