### PR TITLE
Add 'Gothaer Digital GmbH' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gothaer-digital_1671366512407%2Fcompanies%2Fgothaer-digital.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by baltpeter** [comment]
The website doesn't load for me anymore. Do you know whether they are still active? (Sorry for taking so long with getting to the PR!)

**Comment by WebworkrNet** [comment]
Hi @baltpeter, https://www.gothaer-digital.de and https://www.gothaer-digital.de/data-privacy load without problems. Can you try again?

**Comment by baltpeter** [comment]
How weird, for some reason my PiHole doesn't respond for that domain, even though it isn't on any of the blocklists I'm using… Anyway, I can check reach the site with another DNS server, thanks for checking.

**Review by baltpeter — APPROVED** [review]
Thank you!

**Comment by WebworkrNet** [comment]
> How weird, for some reason my PiHole doesn't respond for that domain, even though it isn't on any of the blocklists I'm using… Anyway, I can check reach the site with another DNS server, thanks for checking.

No problem, it's called collaboration :-)

**Pull request merged**
