### PR TITLE
Add 'Vonza HQ' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22vonza%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Vonza%20HQ%22%2C%22address%22%3A%2212600%20Deerfield%20Pkwy%2C%20Suite%20100%20USA%22%2C%22phone%22%3A%228886402951%22%2C%22email%22%3A%22info%40vonza.com%22%2C%22web%22%3A%22https%3A%2F%2Fvonza.com%2F%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1171%22%5D%7D)**

### CODE REVIEW

**Comment by fm** [comment]
Their Privacy Policy link leads to a 404. Emailed them to fix, will fill any changed info once it's fixed.

**Comment by baltpeter** [comment]
Through a bit of trial and error: https://vonza.com/privacypolicy works :D

**Comment by fm** [comment]
Nice! I tried a couple of combinations, but didn't try to make the existing link lowercase.

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
