### PR TITLE
Update 'MediaMarkt.de' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mediamarkt_1691592912373%2Fcompanies%2Fmediamarkt.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
As part of the even closer integration of MediaMarkt and Saturn, there were probably some name changes. It would therefore be appropriate if someone could also check the data set for Saturn to ensure that it is up-to-date.

https://www.datenanfragen.de/company/saturn-shop

**Comment by WebworkrNet** [comment]
I have removed the phone number from the data record because it is not mentioned in the data protection declaration.

**Comment by mal-tee** [comment]
> I have removed the phone number from the data record because it is not mentioned in the data protection declaration.

I haven't had the chance yet to look at the record, but if there is no phone no. in the privacy policy its totally okay to fall back to the regular phone number :+1:

**Comment by WebworkrNet** [comment]
Related to #1283, #1284, #2400, #2401.

**Comment by baltpeter** [comment]
Thanks! Since there were merge conflicts and some updates to related records, I've implemented the changes through https://github.com/datenanfragen/data/commit/0787efd91e896de8228efc593780b5ee8e0944b3.

**Pull request closed without merging**
