### PR TITLE
Add 'Studierendenschaft der Johannes Gutenberg-Universität Mainz K.d.ö.R.' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_studierendenschaft-der-johannes-gutenberg-universit-t-mainz-k-d-r_1672401596593%2Fcompanies%2Fstudierendenschaft-der-johannes-gutenberg-universit-t-mainz-k-d-r.json )**

### CODE REVIEW

**Review by mal-tee — APPROVED** [review]
Thank you!

**Comment by Gusser93** [comment]
@mal-tee 
You removed the .json file extension in commit https://github.com/datenanfragen/data/pull/2022/commits/9c7c48f1321a461cf7b36c4f9ac206a7c98e8872. I think this prevents this entry to be displayed.

**Comment by mal-tee** [comment]
Thank you! I shouldn't use Web-GUIs to edit files anymore... :D

**Comment by mal-tee** [comment]
Fixed in https://github.com/datenanfragen/data/commit/cd67c194f4ab149ad9d85809503310a9fb2bfa05

**Pull request merged**
