### PR TITLE
Add 'Stage Entertainment' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22stage-entertainment%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22it%22%2C%22gb%22%2C%22nl%22%2C%22fr%22%2C%22es%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Stage%20Entertainment%22%2C%22address%22%3A%22STAGE%20ENTERTAINMENT%20Marketing%20%26%20Sales%20GmbH.%5CnDatenschutz%5CnKehrwieder%206%5Cn20457%20Hamburg%22%2C%22email%22%3A%22datenschutzbeauftragter%40stage-entertainment.de%20%22%2C%22web%22%3A%22https%3A%2F%2Fwww.stage-entertainment.de%2Fservice%2Fdatenschutz.html%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.stage-entertainment.de%2Fservice%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fwww.stage-entertainment.com%2Fcompanies%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F959%22%5D%2C%22required-elements%22%3A%5B%7B%22type%22%3A%22input%22%7D%5D%2C%22comments%22%3A%5B%22Ob%20f%C3%BCr%20jede%20L%C3%A4ndergesellschaft%20noch%20ein%20separater%20DSB%20bestellt%20ist%2C%20m%C3%BCsste%20noch%20einmal%20%C3%BCberpr%C3%BCft%20werden.%22%5D%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by mal-tee** [comment]
Thanks! Because these are different legal companies, we should split this into multiple records.

**Comment by WebworkrNet** [comment]
identification identification is not required (Stage Entertainment Marketing & Sales GmbH).

**Review by mal-tee — DISMISSED** [review]
Thank you and sorry for the delay!

**Review by mal-tee — APPROVED** [review]

**Comment by WebworkrNet** [comment]
> Thanks! Because these are different legal companies, we should split this into multiple records.

For the sake of completeness: The answer referred to the following comment in the data set: 

 "Ob für jede Ländergesellschaft noch ein separater DSB bestellt ist, müsste noch einmal überprüft werden."

("Whether a separate DPO is still appointed for each national company would have to be re-examined.")

**Pull request merged**
