### PR TITLE
Add Portuguese translations for some templates

### PR DESCRIPTION
**Pull request by isaacgdo**
New templates:

- access-default.txt
- access-tracking.txt
- admonition.txt
- complaint.txt
- erasure-default.txt

### CODE REVIEW

**Comment by zner0L** [comment]
Hey @isaacgdo, thank you so much! Is this Brazilian Portuguese or Portuguese Portuguese? I just told @marcelosantos89 that we would like the current `pt` directory containing only `pt-br` translations to be renamed into `pt-br` and `pt-pt` translations should be put into a `pt` directory.

**Comment by isaacgdo** [comment]
Hi, @zner0L. Yes, its Brazilian Portuguese. Following the file that was already in ** pt/ **. So, you can just accept the PR and than rename folder to **pt-br/ **

**Comment by marcelosantos89** [comment]
@zner0L I can translate it to pt-pt would you like to open a issue for that and assign to me ?

**Comment by zner0L** [comment]
Cool @isaacgdo, thank you very much!

@marcelosantos89 We don't have separate issues for that, just write a quick message in #229 to let others know you are working on that :)

**Pull request merged**
