### PR TITLE
Update 'radio.de GmbH' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_radio-de_1680872873224%2Fcompanies%2Fradio-de.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
Also operates:
- radio.net
- radiome.de
- radiome.at
- radiome.fr
- ua.radiome.com

The list of countries would still need to be adjusted.

_Originally posted by @WebworkrNet in https://github.com/datenanfragen/data/issues/1749#issuecomment-1135932809_

**Review by baltpeter — APPROVED** [review]
Thank you!

**Comment by WebworkrNet** [comment]
Related to #2579.

**Pull request merged**
