### PR TITLE
Update 'SPIEGEL-Gruppe' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22spiegel-de%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%2C%22commerce%22%2C%22ads%22%5D%2C%22name%22%3A%22SPIEGEL-Gruppe%22%2C%22runs%22%3A%5B%22DER%20SPIEGEL%20GmbH%20%26%20Co.%20KG%22%2C%22DER%20SPIEGEL%20(online)%20(www.spiegel.de)%22%2C%22DER%20SPIEGEL%20Abo%20(abo.spiegel.de)%22%2C%22manager%20magazin%20(www.manager-magazin.de)%22%2C%22manager%20lounge%22%2C%22Harvard%20Business%20Manager%20(www.harvardbusinessmanager.de)%22%2C%22Planestream%20(www.planestream.de)%22%2C%22bento%20(www.bento.de)%22%5D%2C%22address%22%3A%22Ericusspitze%201%5Cn20459%20Hamburg%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2040%20380800%22%2C%22email%22%3A%22datenschutz%40spiegelgruppe.de%22%2C%22web%22%3A%22http%3A%2F%2Fwww.spiegelgruppe.de%22%2C%22sources%22%3A%5B%22http%3A%2F%2Fwww.spiegel.de%2Fextra%2Fdatenschutzerklaerung-so-gehen-wir-mit-ihren-daten-um-a-1207780.html%22%2C%22http%3A%2F%2Fwww.spiegel.de%2Fimpressum%2Fa-941280.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1453%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
"Spiegel Online" ("SPON" for short) has since been renamed "`Der Spiegel (online)`" and restructured. 

Compare:
Page "Der Spiegel (online)". In: Wikipedia - The free encyclopaedia. Edited: 1 August 2021, 07:42 UTC. URL: https://de.wikipedia.org/w/index.php?title=Der_Spiegel_(online)&oldid=214396187 (retrieved: 14 October 2021, 03:26 UTC).

**Comment by WebworkrNet** [comment]
Since it is unclear without further research whether "`DER SPIEGEL GmbH & Co. KG`" is responsible for other websites or services besides `spiegel.de`, I have also listed the company.

**Comment by baltpeter** [comment]
Sorry for taking so long with the review, I have now dug into this.

According to the [privacy policy](https://www.spiegel.de/datenschutz-spiegel), "Datenschutzrechtlich verantwortlich ist das jeweils im Impressum genannte Unternehmen der SPIEGEL-Gruppe." And "DER SPIEGEL GmbH & Co. KG" is only listed on spiegel.de, the other sites we previously listed under `runs` (now?) are run by different companies. I've thus removed them.

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
