### PR TITLE
Introduce "webform" field and update SVA details

### PR DESCRIPTION
**Pull request by baltpeter**
This is in preparation for datenanfragen/website#401.

This is one of those cases where I would appreciate a review from both of you (especially for the first commit and whether that's how we want to implement this).

Things I still need to do:

* [x] Write the `schema` issue.
* [x] Implement the changes for the SVAs and collect all their web forms.

### CODE REVIEW

**Comment by baltpeter** [comment]
Pretty much what I said here: https://github.com/datenanfragen/website/issues/401#issuecomment-695180685

I don't think it's (realistically) possible to do anything other than link the form and offer the user to copy the text manually.

**Comment by baltpeter** [comment]
I would change the stm, yes. That just isn't implemented yet because it would obviously break `website`.

As for the req-elems: From experience, a lot of these forms are just contact forms where you can select "privacy request" or something like that as the subject. But if the form asks for specific ID elements (and we consider them reasonable), then yes, I would add them as req-elems.

**Comment by mal-tee** [comment]
*bump* @zner0L

**Review by mal-tee — APPROVED** [review]

**Review by zner0L — DISMISSED** [review]
There is nothing blocking this actually, i don't know why I didn't approve this. The thing I am concerned about is the UX for this, but this PR has nothing to do with it. @baltpeter what about the WIP status of the PR?

**Comment by baltpeter** [comment]
Great! Now that we have your okay for the schema, I can bring the PR up-to-date and de-WIP it.

**Comment by baltpeter** [comment]
I have rebased on master and fixed the conflicts. I still need to make the changes for the newly added webforms.

**Comment by baltpeter** [comment]
I'm currently working on moving the web form comments in SVAs to `webform` and updating the records while I'm at it (quite a few are outdated :/).

Annoyingly, https://www.ldi.nrw.de/ seems to be down right now. -.-

**Comment by baltpeter** [comment]
Ok, I've now gone through all SVA and updated their details (a _lot_ were outdated :/). The LDI NRW website has also come back online.

With that, this is ready for review. But as mentioned in #2099, https://github.com/datenanfragen/website/pull/1022 should be merged first.

**Comment by baltpeter** [comment]
The AppVeyor test runs against the schema on master, so the fail is expected.

**Review by mal-tee — APPROVED** [review]
Thank you!

**Review by zner0L — APPROVED** [review]
I just merged https://github.com/datenanfragen/website/pull/1022, so now we can merge this, as soon as everything has deployed.

**Pull request merged**
