### PR TITLE
Add inwx.de

### PR DESCRIPTION
**Pull request by nodeg**

### CODE REVIEW

**Comment by m-rey** [comment]
Are there some "required-elements"?
Normally it is the name and the address.

**Comment by baltpeter** [comment]
@nodeg Thanks for the PR, looks good! Adding required elements as @m-rey suggested would be great but if you don't know them, that's fine, too.

@m-rey Thanks for helping with the review. Would you be interested in being added as a collaborator to this repo? You know the guidelines now and having some help in managing contributions would be great! Let me know if you're interested. :)  
I'll also add CI checks soon to automatically catch common errors in PRs.

**Comment by m-rey** [comment]
@baltpeter Yes, I would love to!
But please keep reviewing my PRs ;)

CI checks? That would be very helpful

**Comment by baltpeter** [comment]
@m-rey Awesome, just invited you as a collaborator!

No worries, I will. :D 

The CI checks have also been implemented already (see #315 for an example). This was pretty easy as I already had the test script as a local git hook.

**Pull request merged**
