### PR TITLE
Add 'Sparkasse Sparkasse' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22sparkasse-hannover%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Sparkasse%20Sparkasse%22%2C%22address%22%3A%22Raschplatz%204%5Cn30161%20Hannover%5CnDeutschland%22%2C%22email%22%3A%22datenschutzbeauftragter%40sparkasse-hannover.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.sparkasse-hannover.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.sparkasse-hannover.de%2Fde%2Fhome%2Ftoolbar%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1271%22%5D%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
It should of course be `Sparkasse Hannover` instead of ~`Sparkasse Sparkasse`~.

I tried to change this in the editor, but failed at the final save. What do I have to do so that the updated values are transferred to the file?

**Comment by fm** [comment]
Do you mean the company editor on datarequests.org or the builder at https://company-json.datenanfragen.de? If the latter, you need to click on **_Generate_** after each change.

**Review by fm — APPROVED** [review]

**Comment by WebworkrNet** [comment]
> the builder at https://company-json.datenanfragen.de? If the latter, you need to click on **_Generate_** after each change.

Hm, don't know what went wrong. Thanks for the info, will try again next time.

**Comment by mal-tee** [comment]
If you tried to commit to *this* Pull Request, then it didn't work because only maintainers can update records suggested through [datenanfragen.de/suggest](datenanfragen.de/suggest). As the repository/branch is owned by our https://github.com/datenanfragen-community-edits bot.

Because you are a recurring suggester, I recommend filing PRs yourself through your own Github-Account. That would allow you to submit multiple records at once and update your own records according to our review or our tests. You also wouldn't need to notify us that you made this PR. (If you need another incentive: We will host another Hacktoberfest event, [like last year](https://www.datenanfragen.de/blog/hacktoberfest-2020/). Filing PRs yourself and registering to our event will give you a chance to win goodies. :) )

Our typical workflow to add new companies is using company-json.datenanfragen.de, downloading the files and then committing them to git. Either through GitHub, e.g.:
image
or your favorite git client to add a new company. Committing through GitHub will create a so-called fork on your Github-Account, so to say a working copy for you. 

If you want to use another client, you'll have to fork the repository first and then commit to that fork on your account. If you want to know more, there are plenty of guides online on working with git and GitHub.

After you've made your changes to your fork, you can create a Pull Request. GitHub will show a handy button on top of the repository.

The company-json.datenanfragen.de tool is a bit more complex than /suggest, but offers some advanced features, for example integrated tests. If you encounter new or weird fields, just ignore them, you don't have to fill them. For example, we rarely use "needs-id-document", that why we don't show it in our /suggest-interface.

**Comment by WebworkrNet** [comment]
Could someone rename the title of the PR to `Sparkasse Hannover`? Thanks

**Comment by baltpeter** [comment]
Sure, done.

**Comment by WebworkrNet** [comment]
@mal-tee Thank you for the detailed explanations, now I see more clearly.

Own PRs are an interesting alternative for later. At the moment I'm on the road with a mobile device. I think the generator via the website is the better option at the moment.

My question by e-mail is answered. :-)

**Pull request merged**
