### PR TITLE
Fix grammar error in Dutch erasure request

### PR DESCRIPTION
**Pull request by attaxia**
geld -> geldt
stam + t

### CODE REVIEW

**Comment by baltpeter** [comment]
Thanks, @attaxia!

Since I don't speak Dutch, could you please have a look at this, @MrWouterNL? :)

**Comment by MrWouterNL** [comment]
@baltpeter 

@attaxia is right, it should definitely be 'dit geldt'

**Review by baltpeter — APPROVED** [review]
Thanks, @attaxia and @MrWouterNL!

**Comment by attaxia** [comment]
My quickest and smallest PR yet.

**Pull request merged**
