### PR TITLE
Add 'BigClick GmbH & Co.KG' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_big-click_1679967355272%2Fcompanies%2Fbig-click.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
Provider may also operate other sites (e.g. https://schulferien.orgabird.de). However, I have not checked this further.

**Comment by WebworkrNet** [comment]
Please withhold publication of the record. There are problems with delivery using the email address provided.

**Comment by WebworkrNet** [comment]
I hereby rescind the request for deferral.

I have used the wrong email address: `datenschutz@blick-click.com` instead of `datenschutz@big-click.com`.

**Comment by WebworkrNet** [comment]
### This dataset can be marked as "`tested`".

**Personal data provided at data request:**

- [x] Email address
- [x] Name
- [ ] Address
- [ ] Birth date
- [ ] Other

**Evidence requested to confirm identity:**
 
- [X] No provision of evidence
- [ ] Requests by email must be made from the same email address that is the subject of the request. This should be noted if the submitted address is an email forwarding address.
- [ ] Birth date
- [ ] Copy of ID

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
