### PR TITLE
Update 'Fielmann AG' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_fielmann-de_1695826538035%2Fcompanies%2Ffielmann-de.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
Related to #2368.

**Comment by mal-tee** [comment]
> I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de). You can contact me if you have any questions.

I assume we can set the state of the record with your changes from this PR to `tested`?

**Comment by WebworkrNet** [comment]
> > I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de). You can contact me if you have any questions.
> 
> I assume we can set the state of the record with your changes from this PR to `tested`?

Yes, compare https://github.com/datenanfragen/data/pull/2368#issue-1915760078.
Thank you

**Pull request merged**
