### PR TITLE
Update 'Deutsche Messe AG' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_deutsche-messe_1644439624643%2Fcompanies%2Fdeutsche-messe.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
### This dataset can be marked as "`tested`".

**Personal data provided at data request:**

- [x] Email address
- [x] Name
- [ ] Address
- [ ] Birth date
- [ ] Other

**Evidence requested to confirm identity:**
 
- [x] No provision of evidence
- [ ] Requests by email must be made from the same email address that is the subject of the request. This should be noted if the submitted address is an email forwarding address.
- [ ] Birth date
- [ ] Copy of ID

**Review by baltpeter — APPROVED** [review]
Thank you!

I've removed the comment about the external DPO as the [messe.de privacy policy](https://www.messe.de/de/datenschutz/datenschutz.xhtml) says:

> Für die Ausübung von den Betroffenenrechten wenden Sie sich an [datenschutz@messe.de](mailto:datenschutz@messe.de) .

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
