### PR TITLE
Add 'Domoguide' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22domoguide%22%2C%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Domoguide%22%2C%22address%22%3A%226%20chemin%20de%20Baudin%2C%20B104%20%E2%80%93%2033320%20Le%20Taillan-M%C3%A9doc%22%2C%22email%22%3A%22admin%40domoguide.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.domoguide.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.domoguide.com%2Fconditions-generales-dutilisation%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1058%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by fm** [comment]
This site doesn't seem to store any personal data?

**Comment by tlwt** [comment]
Maybe they do send out unsolicited emails / letters.

**Comment by mal-tee** [comment]
I don't think that we should judge if a company might process personal data. If it is in scope of the GDPR, we can use it :D

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
