### PR TITLE
Update 'Heise Medien GmbH & Co. KG' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_heise-de_1686802674899%2Fcompanies%2Fheise-de.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
I have removed phone and fax numbers from the original record as they are not specific contact information for the Privacy Officer.

**Comment by WebworkrNet** [comment]
#2209 contains a supplementary entry on entities and services.

**Comment by baltpeter** [comment]
> I have removed phone and fax numbers from the original record as they are not specific contact information for the Privacy Officer.

Actually, if there are no privacy-specific contact details, we _do_ fall back to the general support details, see our README: https://github.com/datenanfragen/data#data-sources

The purpose of our DB is not to collect DPO details, but the contact details that people should use to contact the company for privacy-related questions. If there no privacy-specific details, the general details are fine for that.

**Review by baltpeter — APPROVED** [review]
Thank you!

**Comment by WebworkrNet** [comment]
_Originally posted by @baltpeter in https://github.com/datenanfragen/data/issues/2209#issuecomment-1768101228_

> Thank you! I've merged this through #2421 as I wasn't allowed to edit your master branch. I've removed the Heise changes, since those were already merged through #2217.

So both updates to `Heise Medien GmbH & Co. KG` from #2209 and #2217 were combined in #2217 and then added to `datenanfragen:master`, correct?

**Comment by baltpeter** [comment]
As far as I could see, yes.

**Pull request merged**
