### PR TITLE
Add 'Mantle Germany GmbH' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_infratest-dimap_1695819249456%2Fcompanies%2Finfratest-dimap.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
The contact data should be adapted:

> Infratest dimap
> Gesellschaft für Trend- und Wahlforschung mbH
> Alt-Moabit 96a
> D-10559 Berlin

Compare imprint (https://www.infratest-dimap.de/kontakt/impressum/).

The contact details listed in the community proposal are those of the external data protection officer:

> Mantle Germany GmbH
> Landsberger Str. 284, 80687 München
> E-Mail: `datenschutz.kantarpublic@kantar.com`
> Telefon: 0800 000 1468

Compare privacy statement (https://www.infratest-dimap.de/kontakt/datenschutz/).

**Comment by baltpeter** [comment]
I do think we should use the details for the DPO. According to the privacy policy (under "Ihre Rechte auf Auskunft, Berichtigung, Sperre, Löschung und Widerspruch"): "Bitte wenden Sie sich dazu an unseren Datenschutzbeauftragten. Die Kontaktdaten finden Sie am Ende dieser Erklärung."

**Review by baltpeter — APPROVED** [review]
Thank you!

**Comment by WebworkrNet** [comment]
> I do think we should use the details for the DPO. According to the privacy policy (under "Ihre Rechte auf Auskunft, Berichtigung, Sperre, Löschung und Widerspruch"): "Bitte wenden Sie sich dazu an unseren Datenschutzbeauftragten. Die Kontaktdaten finden Sie am Ende dieser Erklärung."

@baltpeter, I don't agree with that. The person responsible and the data protection officer are two different things.

Responsible for processing the data is:

> Infratest dimap
> Society for Trend and Election Research mbH
> Alt Moabit 96a
> D-10559 Berlin

Compare [Verantwortlich für die Verarbeitung Ihrer Daten](https://www.infratest-dimap.de/kontakt/datenschutz/#element22)

The data set currently states that Mantle Germany GmbH is the operator and is accordingly responsible. However, Mantle Germany GmbH is only the data protection officer.

Compare https://www.datenanfragen.de/company/infratest-dimap.

So far we have always made a clear distinction.

**Pull request merged**
