### PR TITLE
Update `Sächsische Datenschutz- und Transparenzbeauftragte`

### PR DESCRIPTION
**Pull request by WebworkrNet**
Email address and URLs updated.

### CODE REVIEW

**Comment by baltpeter** [comment]
Thank you! Since this PR had some unrelated changes, I've merged it through https://github.com/datenanfragen/data/commit/712ce3bdc720cd7488c6834e374142d07fd98786.

**Comment by WebworkrNet** [comment]
> This pull request is closed, but the WebworkrNet:WebworkrNet-patch-1 branch has unmerged commits. 

Can I delete this branch or would this currently have an impact on the still open PRs #2209 and #2368? Thanks

**Comment by baltpeter** [comment]
Those two PRs are for different branches (WebworkrNet:master and WebworkrNet:WebworkrNet-Fielmann, whereas this one is WebworkrNet:WebworkrNet-patch-1), so they shouldn't be impacted.

**Comment by WebworkrNet** [comment]
`WebworkrNet-patch-1`branch deleted.

**Pull request closed without merging**
