### PR TITLE
Update 'Gothaer Versicherungsbank VVaG' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gothaer_1671363814894%2Fcompanies%2Fgothaer.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
### This dataset can be marked as "`tested`".

**Personal data provided at data request:**

- [x] Email address
- [x] Name
- [x] Address
- [ ] Birth date
- [ ] Other

**Evidence requested to confirm identity:**
 
- [x] No provision of evidence
- [ ] Requests by email must be made from the same email address that is the subject of the request. This should be noted if the submitted address is an email forwarding address.
- [ ] Birth date
- [ ] Copy of ID

**Comment by WebworkrNet** [comment]
Provider replied by registered mail via traditional mail.

**Comment by WebworkrNet** [comment]
Regarding a query about the progress of my inquiry, someone from Gothaer Finanzholding AG answered me. Should this entry be re-listed under this company name and "Gothaer Versicherungsbank VVaG" be better listed as "also operates" instead?

**Comment by WebworkrNet** [comment]
New postal address:
> Arnoldiplatz 1
> 50969 Köln

**Comment by WebworkrNet** [comment]
> Regarding a query about the progress of my inquiry, someone from Gothaer Finanzholding AG answered me. Should this entry be re-listed under this company name and "Gothaer Versicherungsbank VVaG" be better listed as "also operates" instead?

I withdraw my proposal.

The privacy statement mentions "**_Gothaer Versicherungsbank VVaG_**".

https://www.gothaer.de/rechtliche-informationen/datenschutz/

Instead, list "Gothaer Finanzholding AG" under "also operates"?

**Comment by WebworkrNet** [comment]
Contact form (securely encrypted):

https://www.gothaer.de/rechtliche-informationen/datenschutz/kontakt-datenschutzbeauftragter.htm

**Comment by baltpeter** [comment]
> Instead, list "Gothaer Finanzholding AG" under "also operates"?

We would need a (public, preferably official) source for that. I didn't find "Gothaer Finanzholding AG" in any of the privacy policies listed [here](https://www.gothaer.de/rechtliche-informationen/datenschutz/), unfortunately.

**Review by baltpeter — APPROVED** [review]
Thank you!

**Comment by WebworkrNet** [comment]
> > Instead, list "Gothaer Finanzholding AG" under "also operates"?
> 
> We would need a (public, preferably official) source for that. I didn't find "Gothaer Finanzholding AG" in any of the privacy policies listed [here](https://www.gothaer.de/rechtliche-informationen/datenschutz/), unfortunately.

I could contact Gothaer again and point this out to them. Should I?

In my experience, data protection declarations and the like are not always carefully and regularly maintained. Changes are often only incorporated into these documents after a delay or not at all.

**Comment by baltpeter** [comment]
> I could contact Gothaer again and point this out to them. Should I?

Sure, if you want to do that. Otherwise, it seems like the request also went fine with the current details, so it doesn't seem to matter too much. *shrug*

> In my experience, data protection declarations and the like are not always carefully and regularly maintained. Changes are often only incorporated into these documents after a delay or not at all.

That's definitely my experience as well. I recently had quite a lot of "fun" trying to find the correct details for the Rundfunkdatenschutzbeauftragter because there were many different (and outdated) versions of privacy policies (#2100). :D

**Pull request merged**
