### PR TITLE
Update 'Microsoft Ireland Operations Ltd.' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_microsoft_1681285252993%2Fcompanies%2Fmicrosoft.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
The changes are based on this web form: https://www.microsoft.com/de-de/concern/privacy ("To which product is your question about data protection assigned?")

**Comment by WebworkrNet** [comment]
"Wunderlist" was discontinued in favour of "To Do", compare https://en.wikipedia.org/wiki/Wunderlist.

**Review by mal-tee — APPROVED** [review]
Thank you!

**Pull request merged**
