### PR TITLE
Update 'Springer Nature'

### PR DESCRIPTION
**Pull request by lucasmchoi**
Add "requested-language": "en"
and mark as "tested"

### CODE REVIEW

**Comment by lucasmchoi** [comment]
Corrected all sources of CI fails

**Comment by fm** [comment]
@lucasmchoi Do they not answer requests in German? 

Here are the guidelines for setting the `request-language`: https://github.com/datenanfragen/data#request-language

**Comment by lucasmchoi** [comment]
@fm They responded in English, even though I sent my request in German. So I guess both languages are fine for them.

**Review by fm — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
