### PR TITLE
Add 'NV Coca‑Cola Services SA' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22coca-cola-deutschland%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22NV%20Coca%E2%80%91Cola%20Services%20SA%22%2C%22runs%22%3A%5B%22https%3A%2F%2Fwww.coca-cola.de%22%5D%2C%22address%22%3A%22Chauss%C3%A9e%20de%20Mons%201424%5Cn1070%20Br%C3%BCssel%22%2C%22web%22%3A%22https%3A%2F%2Fwww.coca-cola-deutschland.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.coca-cola-deutschland.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1279%22%5D%2C%22comments%22%3A%5B%22Es%20ist%20davon%20auszugehen%2C%20dass%20der%20Anbieter%20zahlreiche%20weitere%20Webangebote%20betreibt.%22%5D%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Review by fm — APPROVED** [review]
Thank you!

**Comment by WebworkrNet** [comment]
Thanks for the corrections

**Comment by WebworkrNet** [comment]
Can someone change the title of the PR to `Coca-Cola GmbH`? Thanks

**Pull request merged**
