### PR TITLE
Add 'World-of-Smilies' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22world-of-smilies%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22World-of-Smilies%22%2C%22address%22%3A%22Sebastian%20Messerich%5CnHerrlichkeit%202%2C%2027283%20Verden%20%2F%20Aller%22%2C%22email%22%3A%22webmaster%40world-of-smilies.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.world-of-smilies.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.world-of-smilies.com%2Fimpressum.htm%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1266%22%5D%2C%22comments%22%3A%5Bnull%5D%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
The e-mail address given in the imprint cannot be reached under TLD "`.de`". A renewed attempt at "`.com`" has so far _not_ resulted in any errors, so I assume that the latter exists.

**Comment by WebworkrNet** [comment]
I have deliberately omitted the telephone number, as the imprint only gives a chargeable 0900 number.

**Review by fm — APPROVED** [review]
They seem to have different MX's too - maybe it hasn't been updated in a while.
In any case, thank you!

**Comment by baltpeter** [comment]
> I have deliberately omitted the telephone number, as the imprint only gives a chargeable 0900 number.

In those cases, we usually do add the number and have a comment explaining that it is a paid number. However, given the ridiculously high cost in this case, I agree with the omission.

**Comment by WebworkrNet** [comment]
@baltpeter OK, thanks for the info.

**Pull request merged**
