### PR TITLE
Add 'Canada Life Assurance Europe plc' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_canadalife_1673997085125%2Fcompanies%2Fcanadalife.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
- The company has a separate postal address according to the imprint. Should this be taken into account?

- It looks to me as if the company has appointed an external data protection officer. Should his address be taken into account?

**Comment by baltpeter** [comment]
> * The company has a separate postal address according to the imprint. Should this be taken into account?
> 
> * It looks to me as if the company has appointed an external data protection officer. Should his address be taken into account?

We only care about the address for privacy requests. Sometimes, the privacy policy explicitly states which contact details to use for requests (e.g. companies with external DPOs sometimes want you to still contact some internal address for requests). If that's the case, we use those details. Otherwise, we default to the DPO (external or internal) details if available.

In this case, the [privacy policy](https://www.canadalife.de/media/datenschutzhinweise-bei-beantragung-eines-versicherungsvertrags-gemaess-artikel-13-dsgvo.pdf) only says "Sie können unter der oben genannten Adresse Auskunft über die zu Ihrer Person gespeicherten Daten verlangen.", so they don't seem to have a preference and I'll use the DPO's details.

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
