### PR TITLE
Update 'Reddit Netherlands B.V.' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_reddit_1709684671909%2Fcompanies%2Freddit.json )**

### CODE REVIEW

**Comment by therealdylansteele** [comment]
Reddit nó longer responds to direct emails we must use the contact form to submit gdpr requests.

**Comment by baltpeter** [comment]
Curiously, the [privacy policy](https://www.reddit.com/policies/privacy-policy#policy-h2-7) still says:

> If you have questions or are not able to submit a request to exercise your rights using the mechanisms above, you may also email us at [redditdatarequests@reddit.com](mailto:redditdatarequests@reddit.com) from the email address that you have verified with your Reddit account, or submit them [here](https://support.reddithelp.com/hc/en-us/requests/new?ticket_form_id=360001370251).

**Comment by mal-tee** [comment]
Let me test this.

**Comment by mal-tee** [comment]
> To request a copy of the data we have about you, please send it from [this form](https://www.reddit.com/settings/data-request) using your account so we know it's really you. Without verification that you are the owner of the account in question, we will not be able to proceed. Once your data is ready, we'll send a private message with a link to download your data to your Reddit account.

**Review by mal-tee — APPROVED** [review]
Thank you!

**Pull request merged**
