### PR TITLE
Update 'Deezer S.A.' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_deezer_1653402085813%2Fcompanies%2Fdeezer.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
```
The mail system

<privacy@deezer.com>: host aspmx.l.google.com[142.251.5.27] said: 550-5.1.1 The
email account that you tried to reach does not exist. Please try 550-5.1.1
double-checking the recipient's email address for typos or 550-5.1.1
unnecessary spaces. Learn more at 550 5.1.1
https://support.google.com/mail/?p=NoSuchUser
i15-20020adfdecf000000b0020ae8105ea6si12247075wrn.180 - gsmtp (in reply to
RCPT TO command)
```

**Comment by WebworkrNet** [comment]
At https://www.deezer.com/legal/personal-datas, reference is made to corresponding forms instead. 

(It could also always be the same form, this would have to be examined more closely).

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
