### PR TITLE
Update 'TVinfo Internet GmbH' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tvinfo_1692398796543%2Fcompanies%2Ftvinfo.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
Related to #2318

**Comment by WebworkrNet** [comment]
The information stored in the comment field is based on a response to a request for information.

**Comment by baltpeter** [comment]
Can you please leave that comment on the [company page](https://www.datenanfragen.de/company/tvinfo) instead (see: https://github.com/datenanfragen/data/pull/2221#issuecomment-1768106557)? Thanks!

**Pull request closed without merging**
