### PR TITLE
Add 'Randstad Deutschland GmbH & Co. KG' / Update 'Heise Medien GmbH & Co. KG' 

### PR DESCRIPTION
**Pull request by WebworkrNet**
My first pull request for this repository. :-)

### CODE REVIEW

**Comment by WebworkrNet** [comment]
> This branch has conflicts that must be resolved

> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

I must have made a mistake with the link "`https://www.heise.de/Individuelle-Datenschutzinformation-fuer-Heise-Business-Services-7099857.html`".

The other conflict I believe can be resolved by accepting my changes.

**Comment by baltpeter** [comment]
Thank you! I've merged this through #2421 as I wasn't allowed to edit your master branch. I've removed the Heise changes, since those were already merged through #2217.

**Comment by WebworkrNet** [comment]
There is a checkbox that I should have activated to allow the maintainer of the datenanfragen.de repository to edit my master branch, right? This is how I remember it from another repository.

**Comment by baltpeter** [comment]
Actually, you _did_ enabled the "Allow edits by maintainers" checkbox for this PR. But it seems like that doesn't work for branches with branch protections enabled (which your master branch on the data repository seems to have). So, you should always make PRs from another branch than the master branch _and_ check the box. That's also preferable in another way: Then you can make sure that your master branch is always up-to-date with ours and you don't have any unrelated changes in your PRs.

**Comment by WebworkrNet** [comment]
The following branches and files can be deleted?

- https://github.com/datenanfragen/data/pull/2209/commits/2786175ea1962ad33bffdedfbb9b9bc405db0651
- https://github.com/datenanfragen/data/pull/2209/commits/4abbadaf03dfc4ecec7362775ae4539ff21c7cf6
- https://github.com/datenanfragen/data/pull/2209/commits/064b1101d0cce4b78051292e3de2651a483175c9
- https://github.com/datenanfragen/data/pull/2209/commits/f64e984be14313659cf3af502a2cade65860718c

Or are there any effects to be expected on #2368? Thanks

**Pull request closed without merging**
