### PR TITLE
Update 'Deutsche Telekom AG' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_vivento_1638939216338%2Fcompanies%2Fvivento.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
I think this data set should be summarised with https://www.datenanfragen.de/company/telekom-de.

**Comment by mal-tee** [comment]
> I think this data set should be summarised with datenanfragen.de/company/telekom-de.

`telekom-de` represents the "GmbH", but vivento is part of the AG. Not sure if we should merge them. But I'll update this record.

**Review by mal-tee — APPROVED** [review]
Thank you!

**Comment by WebworkrNet** [comment]
> > I think this data set should be summarised with datenanfragen.de/company/telekom-de.
> 
> `telekom-de` represents the GmbH, but vivento is part of the AG. Not sure if we should merge them. But I'll update this record.

@mal-tee I agree that they are different companies. However, the contact details of the data protection officer are identical.

**Comment by WebworkrNet** [comment]
Currently, the record is listed on the website as "Vivento". Wouldn't it be cleaner to list the entry as "Deutsche Telekom AG" and "Vivento" under "entities and services" instead?

**Comment by WebworkrNet** [comment]
Why does this pull request not appear as a source on https://www.datenanfragen.de/company/vivento? Wasn't it always the case that older pull requests were also listed?

**Comment by mal-tee** [comment]
>  I agree that they are different companies. However, the contact details of the data protection officer are identical.

Then we usually create a new, separate, record.

> Currently, the record is listed on the website as "Vivento". Wouldn't it be cleaner to list the entry as "Deutsche Telekom AG" and "Vivento" under "entities and services" instead?

If the name is the only thing that changed from the AG record, yes. But I don't think its worth the effort to fix this. @baltpeter Maybe we could introduce a test to check if there are records in the DB that are exact replicas except the company name?

> Why does this pull request not appear as a source on [datenanfragen.de/company/vivento](https://www.datenanfragen.de/company/vivento)? Wasn't it always the case that older pull requests were also listed?

Yes, we keep PRs in this list. Seems like the backend glitched while handling #1678

**Pull request merged**
