### PR TITLE
Update 'HolidayCheck AG' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_holidaycheck_1669703399287%2Fcompanies%2Fholidaycheck.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
The 0800 number is no longer listed in the imprint. In the privacy statement, the telephone and fax numbers are completely omitted. I therefore recommend limiting yourself to the email address.

**Review by baltpeter — APPROVED** [review]
Thank you!

**Comment by WebworkrNet** [comment]
### This dataset can be marked as "`tested`".

**Personal data provided at data request:**

- [x] Email address
- [x] Name
- [ ] Address
- [ ] Birth date
- [ ] Other

**Evidence requested to confirm identity:**
 
- [x] No provision of evidence
- [x] Requests by email must be made from the same email address that is the subject of the request. This should be noted if the submitted address is an email forwarding address.
- [ ] Birth date
- [ ] Copy of ID

**Comment by WebworkrNet** [comment]
@baltpeter Should I open a new pull request for the tested status?

**Comment by baltpeter** [comment]
Thanks @WebworkrNet, I have marked the record as tested. (And sorry for the delay! We're a bit overwhelmed with suggestions right now. :/)

**Comment by WebworkrNet** [comment]
> Thanks @WebworkrNet, I have marked the record as tested. (And sorry for the delay! We're a bit overwhelmed with suggestions right now. :/)

I'm quite relaxed about that. This is not about anything that is time-critical. And all the participants certainly have a life on the side. I don't always answer promptly either.

**Comment by WebworkrNet** [comment]
@baltpeter I can't see on https://www.datenanfragen.de/company/holidaycheck that the privacy contact is marked as tested. Is it the record itself or is it an output/display problem on the website? Thanks

**Comment by baltpeter** [comment]
@WebworkrNet The tested status doesn't show up on company pages, only on other parts of the site like the search bar:

image

Only companies marked as `scraped` or `imported` have special rendering there, e.g. <https://www.datenanfragen.de/company/kirchengemeinde-zum-heiligen-leiden-christi-zu-braunschweig-stoeckheim>.

**Comment by WebworkrNet** [comment]
@baltpeter What does "scraped" mean in this context?

**Comment by mal-tee** [comment]
> @baltpeter What does "scraped" mean in this context?

Hi, it means that the data was collected automatically and without human supervision. Check the "quality"-section in this announcement for more information: https://github.com/datenanfragen/data/issues/690

**Comment by WebworkrNet** [comment]
> > @baltpeter What does "scraped" mean in this context?
> 
> Hi, it means that the data was collected automatically and without human supervision. Check the "quality"-section in this announcement for more information: #690

@mal-tee Thank you

**Comment by WebworkrNet** [comment]
For the record:
https://github.com/datenanfragen/website/issues/1067 is duplicate of https://github.com/datenanfragen/website/issues/784.

**Pull request merged**
