### PR TITLE
Add 'Österreichischer Rundfunk (ORF)' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22orf%22%2C%22relevant-countries%22%3A%5B%22at%22%5D%2C%22name%22%3A%22%C3%96sterreichischen%20Rundfunk%20(ORF)%22%2C%22address%22%3A%22W%C3%BCrzburggasse%2030%5Cn1136%20Wien%5Cn%5Cn%22%2C%22email%22%3A%22datenschutz%40orf.at%22%2C%22web%22%3A%22https%3A%2F%2Fwww.orf.at%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.orf.at%2Fstories%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fwww.orf.at%2Fstories%2Fdatenschutz-rechte%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1273%22%5D%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
Österreichische**r** Rundfunk (ORF)

**Review by mal-tee — APPROVED** [review]
Thank you!

**Comment by WebworkrNet** [comment]
Related to https://github.com/datenanfragen/website/issues/677#issuecomment-922705607, #2389

**Pull request merged**
