### PR TITLE
Update 'dtv Verlagsgesellschaft mbH & Co. KG' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_dtv-verlag_1699121318020%2Fcompanies%2Fdtv-verlag.json )**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
### This dataset can be marked as "`tested`".

**Personal data provided at data request:**

- [x] Email address
- [x] Name
- [ ] Address
- [ ] Birth date
- [ ] Other

**Evidence requested to confirm identity:**
 
- [X] No provision of evidence
- [ ] Requests by email must be made from the same email address that is the subject of the request. This should be noted if the submitted address is an email forwarding address.
- [ ] Birth date
- [ ] Copy of ID

**Comment by WebworkrNet** [comment]
Related to #1274.

**Comment by WebworkrNet** [comment]
The data protection declaration at https://www.dtv.de/datenschutz or https://www.dtv.de/informationen/datenschutz/ provides me with a page with a template, but without data protection content. **Can anybody confirm this?** Thanks

**Comment by baltpeter** [comment]
> The data protection declaration at [dtv.de/datenschutz](https://www.dtv.de/datenschutz) or [dtv.de/informationen/datenschutz](https://www.dtv.de/informationen/datenschutz/) provides me with a page with a template, but without data protection content. **Can anybody confirm this?** Thanks

Yep, same problem for me.

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
