### PR TITLE
Update 'direct services Gütersloh GmbH' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22campaign-services-de%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22direct%20services%20G%C3%BCtersloh%20GmbH%22%2C%22address%22%3A%22Business%20Unit%20Campaign%5CnReinhard-Mohn-Str.%20300%5Cn33333%20G%C3%BCtersloh%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%205241%208040685%22%2C%22fax%22%3A%22%2B49%205241%2080640685%22%2C%22email%22%3A%22info%40campaign-services.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.campaign-services.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.campaign-services.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1205%22%5D%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by mal-tee** [comment]
Seems like the street was renamed: (German source) https://www.nw.de/lokal/kreis_guetersloh/guetersloh/23042721_Jetzt-gibt-es-offiziell-eine-Reinhard-Mohn-Strasse-in-Guetersloh.html

**Comment by mal-tee** [comment]
They didn't update their policy yet.

**Comment by baltpeter** [comment]
> I've emailed to ask when will Datenschutz be corrected.

Seems like that finally did the trick. Thanks!

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
