### PR TITLE
Add 'Future Publishing Limited' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22futureplc%22%2C%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22name%22%3A%22Future%20Publishing%20Limited%22%2C%22runs%22%3A%5B%22Tom's%20Hardware%22%5D%2C%22address%22%3A%22Data%20Protection%20Enquiries%5CnFuture%20Publishing%20Limited%5CnQuay%20House%2C%20The%20Ambury%2C%20Bath%2C%20BA1%201UA%5CnUnited%20Kingdom%22%2C%22phone%22%3A%22%2B44%201225%20442244%22%2C%22email%22%3A%22DPO%40futurenet.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.futureplc.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.futureplc.com%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1153%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by fm** [comment]
Future plc owns 163 brands... I'll see if I can get a list and add them all (unless we don't really need to @baltpeter?)

**Comment by baltpeter** [comment]
163 brands? :o Wow. From a quick glance, it seems like they do indeed all list Future as the controller. As such, I do think it would be helpful to list them under `runs`.

One thing to note: I am currently working on regular automatic verification of whether our records are still up-to-date (see #1158). I would also like to include the `runs` list in that verification as sometimes services are sold to another company etc. But I am not sure yet if that is really feasible. For that, we'd need to have sources that list all the `runs` items so they can automatically be checked.  
In this particular case, the [brands page](https://www.futureplc.com/brands/) unfortunately doesn't include the names but only the logos and a slug (included in the URL)…

**Comment by baltpeter** [comment]
> 163 brands? :o Wow. 

Well, nothing a few lines of JS scraping can't fix. :D And congrats to Future plc for being the longest and most ridiculous record we have (so far…).

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
