### PR TITLE
Update 'Delticom AG' (community contribution)

### PR DESCRIPTION
**Pull request by datenanfragen-community-edits**
This suggestion was submitted through the website.

**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22delticom%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Delticom%20AG%22%2C%22runs%22%3A%5B%22Reifen-Online-Shop%20ReifenDirekt.de%22%2C%22Motorradreifen-Online-Shop%20MotorradreifenDirekt.de%22%2C%22Reifen-Testportal%20Reifentest.com%22%2C%22Komplettr%C3%A4der-Online-Shop%20Komplettraeder24.de%22%5D%2C%22address%22%3A%22Br%C3%BChlstra%C3%9Fe%2011%5Cn30169%20Hannover%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20511%2093634960%22%2C%22fax%22%3A%22%2B49%20511%2087989071%22%2C%22email%22%3A%22datenschutz%40delti.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.delti.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.reifendirekt.de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fwww.motorradreifendirekt.de%2Fi%2Fdatenschutz%22%2C%22http%3A%2F%2Fwww.reifentest.com%2Fwir.html%22%2C%22https%3A%2F%2Fwww.komplettraeder24.de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fwww.reifendirekt.de%2FImpressum.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1275%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**

### CODE REVIEW

**Comment by WebworkrNet** [comment]
I have opened this issue via [datenanfragen.de](https://www.datenanfragen.de).
You can contact me if you have any questions.

**Comment by WebworkrNet** [comment]
The unprofitable business with car parts and engine oil was discontinued.

https://www.delti.com/press/deutsch/deltiP439.html
https://www.delti.com/press/deutsch/deltiP440.html

**Comment by WebworkrNet** [comment]
Overall, however, the list is still incomprehensible. The current list of all web offerings can be viewed at www.delti.com.

**Review by baltpeter — APPROVED** [review]
Thank you!

**Pull request merged**
